app:
  port: ':3300'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2019-09-15T14:04:05'

producer:
  brokers: ['192.168.178.26:9092']
  topic: 'delete.municipality.superhero'
  batch_size: 1
  batch_timeout: 10

health:
  address: '192.168.0.101'
  port: ':8140'
  shutdown_endpoint: '/api/v1/superhero_delete_health/shutdown'
  content_type: 'application/json'